### ISSUE TITLE
Wrong count Hall of Fame

### ISSUE THREAD

**Issue by andre-geraldes** [cesium/intra.seium.org#61]
As spoken today some badges are counting as two. This problem is occuring when we insert the code of an individual use badge.

**Comment by frmendes** [comment]
This is the weirdest one yet. I personally checked this and it happens for Single User badges, which appear to count as 2 in the user badge count.

I was able to restore every badge count to a consistent state by resetting the counters, but I have no idea why it happens since Rails should be managing them. I removed the faulty query from last year, so I don't think this should be an issue with the `counter_cache`.

I'll see what I can do, but I was baffled by this one, today. If anyone else wants to jump in, I'm all up for help.

PS: I've just given you the `Bug Catcher` badge. Congrats!

**Comment by frmendes** [comment]
I'm marking this as a wontfix because we don't have the time to debug this mid-way through the conference.

I've hardcoded an ugly fix. It works, but it's ugly and I'm very sorry.
